import { Component, OnInit, AfterViewInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-tables',
  templateUrl: './tables.component.html',
  styleUrls: ['./tables.component.css']
})
export class TablesComponent implements OnInit {

  num = 3;
  data: Sample[] = [];

  constructor(private http: HttpClient, private route: ActivatedRoute, private router: Router) { }

  ngOnInit() {
    this.route.queryParamMap.subscribe(params => {
      if (params.has('num')) {
        this.num = +params.get('num');
      }
    });

    this.http.get('http://www.mocky.io/v2/5c9e523f3000005500ee97cf').subscribe((data: Sample[]) => {
      this.data = data;
    });
  }

}

// Generated by https://quicktype.io

export interface Sample {
  Name:         string;
  Position:     string;
  Office:       string;
  Age:          string;
  "Start date": string;
  Salary:       string;
}
